- name: "Creates directory"
  become: yes
  file:
    path: "/srv/stg"
    state: "directory"
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "/root/project/artifact.tar.gz"
    dest: "/srv/stg"

- name: "Extract backend to folder"
  unarchive:
    remote_src: yes
    src: "/srv/stg/artifact.tar.gz"
    dest: "/srv/stg"

- name: "Start web server"
  shell:
    cmd: |
      cd /srv/stg
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready
      pm2 status
